### ISSUE TITLE
Training strategy for each class?!

### ISSUE THREAD

**Issue by Mshz2** [rvorias/ind_knn_ad#16]
Hi!
In your custom dataset guideline, you put all good samples into one folder. In my custom dataset, I have three class of objects. I was wondering does it make sense if I train the padim for individual classes and do inference for each class with their seperate models? or it is also ok if I put all classes into one bag of good samples and have one model for all?
I really appreciate your suggestions based on your experience.

Best

**Comment by rvorias** [comment]
Hey thanks for your question.

Because of the way these models work, I'd say it's safer to keep each class separate. However, there are some considerations:
- how will you encounter the classes in production? Will you know the class beforehand? If yes - split the classes. If not - either classify them first and then do anomaly detection, or train a combined model.
- if you really want to combine three classes I'd say PatchCore can handle it a bit better than PaDiM. This is because PatchCore builds a coreset and all three classes will be more or less included. PaDiM models the features as localised normal distributions and that will likely break when your three classes differ a lot.

Hope that sheds some light on your question.
